-- AUTO-GENERATED by tools/threatmodel_compiler. DO NOT EDIT BY HAND.
-- Source threat: Bigquery.T1 — Destruction of data by deleting dataset or table
-- hlgoal: DoS | MITRE tactic: TA0040 | CVSS: Low (3.5)
--
-- Audit log shape assumed: organization-level sink writing to
--   `{audit_project}.{audit_dataset}.cloudaudit_googleapis_com_data_access_*`
--   `{audit_project}.{audit_dataset}.cloudaudit_googleapis_com_activity_*`
-- Configure the scheduled query via the Terraform module in ./terraform/.
SELECT
  TIMESTAMP_TRUNC(timestamp, MINUTE) AS detection_window,
  protopayload_auditlog.authenticationInfo.principalEmail AS actor,
  protopayload_auditlog.methodName AS method_name,
  protopayload_auditlog.resourceName AS resource_name,
  protopayload_auditlog.requestMetadata.callerIp AS caller_ip,
  COUNT(*) AS event_count
FROM `${audit_project}.${audit_dataset}.cloudaudit_googleapis_com_activity_*`
WHERE _TABLE_SUFFIX BETWEEN
        FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
        AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
  AND TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), timestamp, SECOND) <= @lookback_seconds
  AND protopayload_auditlog.methodName IN ('google.cloud.bigquery.v2.TableService.DeleteTable', 'tableservice.delete', 'google.cloud.bigquery.v2.DatasetService.DeleteDataset', 'datasetservice.delete')
  AND protopayload_auditlog.authenticationInfo.principalEmail NOT LIKE '%@gserviceaccount.com'
GROUP BY detection_window, actor, method_name, resource_name, caller_ip
HAVING event_count >= 1
ORDER BY detection_window DESC;
