-- AUTO-GENERATED by tools/threatmodel_compiler. DO NOT EDIT BY HAND.
-- Source threat: Bigquery.T6 — Exfiltration of data by exporting tables to other services
-- hlgoal: DataTheft | MITRE tactic: TA0010 | CVSS: Medium (4.2)
--
-- Audit log shape assumed: organization-level sink writing to
--   `{audit_project}.{audit_dataset}.cloudaudit_googleapis_com_data_access_*`
--   `{audit_project}.{audit_dataset}.cloudaudit_googleapis_com_activity_*`
-- Configure the scheduled query via the Terraform module in ./terraform/.
WITH extract_jobs AS (
  SELECT
    timestamp,
    protopayload_auditlog.authenticationInfo.principalEmail AS actor,
    protopayload_auditlog.requestMetadata.callerIp AS caller_ip,
    protopayload_auditlog.resourceName AS source_resource,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.extractConfig.destinationUris[0]') AS destination_uri,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.extractConfig.sourceTable.tableId') AS source_table,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.type') AS job_type
  FROM `${audit_project}.${audit_dataset}.cloudaudit_googleapis_com_data_access_*`
  WHERE _TABLE_SUFFIX BETWEEN
          FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
          AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
    AND TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), timestamp, SECOND) <= @lookback_seconds
    AND protopayload_auditlog.methodName IN
        ('google.cloud.bigquery.v2.JobService.InsertJob', 'jobservice.insert')
)
SELECT
  TIMESTAMP_TRUNC(timestamp, MINUTE) AS detection_window,
  actor,
  caller_ip,
  source_resource,
  destination_uri,
  source_table,
  COUNT(*) AS extract_event_count
FROM extract_jobs
WHERE job_type = 'EXTRACT'
  AND destination_uri IS NOT NULL
  -- Authorized export sinks should be enumerated in this list; everything else alerts.
  AND NOT REGEXP_CONTAINS(destination_uri, r'^gs://(authorized-export-bucket-1|authorized-export-bucket-2)/')
GROUP BY detection_window, actor, caller_ip, source_resource, destination_uri, source_table
ORDER BY detection_window DESC;
