-- AUTO-GENERATED by tools/threatmodel_compiler. DO NOT EDIT BY HAND.
-- Source threat: Bigquery.T9 — Escalate privileges, loss of availability or integrity of data, or exfiltrate data via an unauthorized query on a dataset or table
-- hlgoal: DataTheft | MITRE tactic: TA0010 | CVSS: High (8.0)
--
-- Audit log shape assumed: organization-level sink writing to
--   `{audit_project}.{audit_dataset}.cloudaudit_googleapis_com_data_access_*`
--   `{audit_project}.{audit_dataset}.cloudaudit_googleapis_com_activity_*`
-- Configure the scheduled query via the Terraform module in ./terraform/.
WITH query_jobs AS (
  SELECT
    timestamp,
    protopayload_auditlog.authenticationInfo.principalEmail AS actor,
    protopayload_auditlog.requestMetadata.callerIp AS caller_ip,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.queryConfig.query') AS query_text,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.queryConfig.statementType') AS statement_type,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobStats.queryStats.totalProcessedBytes') AS bytes_processed,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobStats.queryStats.referencedTables')) AS referenced_table_count
  FROM `${audit_project}.${audit_dataset}.cloudaudit_googleapis_com_data_access_*`
  WHERE _TABLE_SUFFIX BETWEEN
          FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
          AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
    AND TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), timestamp, SECOND) <= @lookback_seconds
    AND protopayload_auditlog.methodName IN
        ('google.cloud.bigquery.v2.JobService.InsertJob', 'jobservice.insert')
),
suspicious AS (
  SELECT *,
    CASE
      WHEN REGEXP_CONTAINS(LOWER(IFNULL(query_text, '')), r'select\s+\*\s+from')
        AND SAFE_CAST(bytes_processed AS INT64) > 1073741824 THEN 'select_star_large_scan'
      WHEN statement_type = 'SELECT'
        AND SAFE_CAST(bytes_processed AS INT64) > 53687091200 THEN 'oversized_scan'
      WHEN referenced_table_count >= 10 THEN 'broad_table_fanout'
      ELSE NULL
    END AS rule_match
  FROM query_jobs
)
SELECT
  TIMESTAMP_TRUNC(timestamp, MINUTE) AS detection_window,
  actor,
  caller_ip,
  rule_match,
  SAFE_CAST(bytes_processed AS INT64) AS bytes_processed,
  referenced_table_count,
  SUBSTR(query_text, 0, 240) AS query_preview
FROM suspicious
WHERE rule_match IS NOT NULL
ORDER BY detection_window DESC, bytes_processed DESC;
