"""Emit BigQuery-native scheduled-query detections + Terraform wrapper.

Design notes
------------
* Detections run **inside** BigQuery against the audit-log sink dataset, so
  there is no external SIEM dependency. This is the headline of the PR.
* The SQL is parameterized with ``@lookback_seconds``, ``@audit_dataset``, and
  ``@audit_table`` so a single artifact can be deployed against any sink layout.
* Per-threat detection logic is hand-tuned — the compiler picks the right
  template based on the threat's permission shape, not a single generic JOIN.
"""
from __future__ import annotations

from dataclasses import dataclass

from ..loader import Threat
from ..permission_map import PermissionSignal


@dataclass
class BigQuerySqlArtifact:
    sql: str
    terraform: str
    description: str


_HEADER = """-- AUTO-GENERATED by tools/threatmodel_compiler. DO NOT EDIT BY HAND.
-- Source threat: {threat_id} — {threat_name}
-- hlgoal: {hlgoal} | MITRE tactic: {tactic} | CVSS: {cvss_severity} ({cvss_score})
--
-- Audit log shape assumed: organization-level sink writing to
--   `{{audit_project}}.{{audit_dataset}}.cloudaudit_googleapis_com_data_access_*`
--   `{{audit_project}}.{{audit_dataset}}.cloudaudit_googleapis_com_activity_*`
-- Configure the scheduled query via the Terraform module in ./terraform/.
"""


def _comma_quoted(values: list[str]) -> str:
    return ", ".join(f"'{v}'" for v in values)


def _detection_for_t1(threat: Threat) -> str:
    methods = ["google.cloud.bigquery.v2.TableService.DeleteTable", "tableservice.delete",
               "google.cloud.bigquery.v2.DatasetService.DeleteDataset", "datasetservice.delete"]
    return f"""
SELECT
  TIMESTAMP_TRUNC(timestamp, MINUTE) AS detection_window,
  protopayload_auditlog.authenticationInfo.principalEmail AS actor,
  protopayload_auditlog.methodName AS method_name,
  protopayload_auditlog.resourceName AS resource_name,
  protopayload_auditlog.requestMetadata.callerIp AS caller_ip,
  COUNT(*) AS event_count
FROM `${{audit_project}}.${{audit_dataset}}.cloudaudit_googleapis_com_activity_*`
WHERE _TABLE_SUFFIX BETWEEN
        FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
        AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
  AND TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), timestamp, SECOND) <= @lookback_seconds
  AND protopayload_auditlog.methodName IN ({_comma_quoted(methods)})
  AND protopayload_auditlog.authenticationInfo.principalEmail NOT LIKE '%@gserviceaccount.com'
GROUP BY detection_window, actor, method_name, resource_name, caller_ip
HAVING event_count >= 1
ORDER BY detection_window DESC;
"""


def _detection_for_t6(threat: Threat) -> str:
    return """
WITH extract_jobs AS (
  SELECT
    timestamp,
    protopayload_auditlog.authenticationInfo.principalEmail AS actor,
    protopayload_auditlog.requestMetadata.callerIp AS caller_ip,
    protopayload_auditlog.resourceName AS source_resource,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.extractConfig.destinationUris[0]') AS destination_uri,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.extractConfig.sourceTable.tableId') AS source_table,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.type') AS job_type
  FROM `${audit_project}.${audit_dataset}.cloudaudit_googleapis_com_data_access_*`
  WHERE _TABLE_SUFFIX BETWEEN
          FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
          AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
    AND TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), timestamp, SECOND) <= @lookback_seconds
    AND protopayload_auditlog.methodName IN
        ('google.cloud.bigquery.v2.JobService.InsertJob', 'jobservice.insert')
)
SELECT
  TIMESTAMP_TRUNC(timestamp, MINUTE) AS detection_window,
  actor,
  caller_ip,
  source_resource,
  destination_uri,
  source_table,
  COUNT(*) AS extract_event_count
FROM extract_jobs
WHERE job_type = 'EXTRACT'
  AND destination_uri IS NOT NULL
  -- Authorized export sinks should be enumerated in this list; everything else alerts.
  AND NOT REGEXP_CONTAINS(destination_uri, r'^gs://(authorized-export-bucket-1|authorized-export-bucket-2)/')
GROUP BY detection_window, actor, caller_ip, source_resource, destination_uri, source_table
ORDER BY detection_window DESC;
"""


def _detection_for_t9(threat: Threat) -> str:
    return """
WITH query_jobs AS (
  SELECT
    timestamp,
    protopayload_auditlog.authenticationInfo.principalEmail AS actor,
    protopayload_auditlog.requestMetadata.callerIp AS caller_ip,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.queryConfig.query') AS query_text,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobConfig.queryConfig.statementType') AS statement_type,
    JSON_VALUE(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobStats.queryStats.totalProcessedBytes') AS bytes_processed,
    ARRAY_LENGTH(JSON_QUERY_ARRAY(protopayload_auditlog.metadataJson,
               '$.jobChange.job.jobStats.queryStats.referencedTables')) AS referenced_table_count
  FROM `${audit_project}.${audit_dataset}.cloudaudit_googleapis_com_data_access_*`
  WHERE _TABLE_SUFFIX BETWEEN
          FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
          AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
    AND TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), timestamp, SECOND) <= @lookback_seconds
    AND protopayload_auditlog.methodName IN
        ('google.cloud.bigquery.v2.JobService.InsertJob', 'jobservice.insert')
),
suspicious AS (
  SELECT *,
    CASE
      WHEN REGEXP_CONTAINS(LOWER(IFNULL(query_text, '')), r'select\\s+\\*\\s+from')
        AND SAFE_CAST(bytes_processed AS INT64) > 1073741824 THEN 'select_star_large_scan'
      WHEN statement_type = 'SELECT'
        AND SAFE_CAST(bytes_processed AS INT64) > 53687091200 THEN 'oversized_scan'
      WHEN referenced_table_count >= 10 THEN 'broad_table_fanout'
      ELSE NULL
    END AS rule_match
  FROM query_jobs
)
SELECT
  TIMESTAMP_TRUNC(timestamp, MINUTE) AS detection_window,
  actor,
  caller_ip,
  rule_match,
  SAFE_CAST(bytes_processed AS INT64) AS bytes_processed,
  referenced_table_count,
  SUBSTR(query_text, 0, 240) AS query_preview
FROM suspicious
WHERE rule_match IS NOT NULL
ORDER BY detection_window DESC, bytes_processed DESC;
"""


_DETECTION_TEMPLATES = {
    "Bigquery.T1": _detection_for_t1,
    "Bigquery.T6": _detection_for_t6,
    "Bigquery.T9": _detection_for_t9,
}


def _terraform_module(threat: Threat) -> str:
    snake_id = threat.short_id.lower()
    return f"""# AUTO-GENERATED. Wraps detect_{snake_id}_*.sql as a BigQuery scheduled query
# and routes findings to a Pub/Sub alert topic. Variables are intentionally lean —
# this module is meant to be invoked from a project-level orchestrator.

terraform {{
  required_version = ">= 1.5.0"
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = ">= 5.20.0"
    }}
  }}
}}

variable "project_id" {{
  type = string
}}

variable "region" {{
  type    = string
  default = "us"
}}

variable "audit_project" {{
  type = string
}}

variable "audit_dataset" {{
  type = string
}}

variable "destination_dataset" {{
  type = string
}}

variable "destination_table" {{
  type    = string
  default = "detections_{snake_id}"
}}

variable "alert_topic" {{
  type = string
}}

variable "lookback_seconds" {{
  type    = number
  default = 3600
}}

variable "schedule" {{
  type    = string
  default = "every 15 minutes"
}}

locals {{
  query_template = file("${{path.module}}/../detect_{snake_id}.sql")
}}

resource "google_bigquery_data_transfer_config" "detection" {{
  display_name           = "ThreatModel detection: {threat.id}"
  location               = var.region
  data_source_id         = "scheduled_query"
  schedule               = var.schedule
  destination_dataset_id = var.destination_dataset

  params = {{
    destination_table_name_template = var.destination_table
    write_disposition               = "WRITE_APPEND"
    query                           = replace(replace(local.query_template,
                                          "$${{audit_project}}", var.audit_project),
                                          "$${{audit_dataset}}", var.audit_dataset)
  }}

  notification_pubsub_topic = var.alert_topic
}}

output "transfer_config_name" {{
  value = google_bigquery_data_transfer_config.detection.name
}}
"""


def emit(threat: Threat, _signals: dict[str, PermissionSignal]) -> BigQuerySqlArtifact | None:
    template = _DETECTION_TEMPLATES.get(threat.id)
    if template is None:
        return None
    tactic = threat.mitre_tactic or "n/a"
    body = template(threat)
    sql = _HEADER.format(
        threat_id=threat.id,
        threat_name=threat.name,
        hlgoal=threat.hlgoal,
        tactic=tactic,
        cvss_severity=threat.cvss_severity,
        cvss_score=threat.cvss_score,
    ) + body.strip() + "\n"
    return BigQuerySqlArtifact(
        sql=sql,
        terraform=_terraform_module(threat),
        description=f"BigQuery scheduled query detecting {threat.name}.",
    )
