"""Emit Microsoft Sentinel KQL queries for GCP audit logs.

Assumes a custom log table ``GCPAuditLogs_CL`` populated by the Sentinel GCP
Pub/Sub data connector. Field names match the standard connector mapping.
"""
from __future__ import annotations

from ..loader import Threat
from ..permission_map import PermissionSignal


_HEADER = """\
// AUTO-GENERATED by tools/threatmodel_compiler. DO NOT EDIT BY HAND.
// Source threat: {threat_id} — {threat_name}
// Table assumption: GCPAuditLogs_CL with fields mirroring protoPayload structure.
"""


_QUERIES = {
    "Bigquery.T1": """
let lookback = 1h;
GCPAuditLogs_CL
| where TimeGenerated > ago(lookback)
| where serviceName_s == "bigquery.googleapis.com"
| where methodName_s in ("google.cloud.bigquery.v2.TableService.DeleteTable",
                         "google.cloud.bigquery.v2.DatasetService.DeleteDataset",
                         "tableservice.delete",
                         "datasetservice.delete")
| where principalEmail_s !endswith "@gserviceaccount.com"
| summarize event_count = count(),
            resources = make_set(resourceName_s),
            caller_ips = make_set(callerIp_s)
        by principalEmail_s, methodName_s, bin(TimeGenerated, 5m)
| where event_count >= 1
""",
    "Bigquery.T6": """
let lookback = 1h;
let authorized_buckets = dynamic(["authorized-export-bucket-1", "authorized-export-bucket-2"]);
GCPAuditLogs_CL
| where TimeGenerated > ago(lookback)
| where serviceName_s == "bigquery.googleapis.com"
| where methodName_s == "google.cloud.bigquery.v2.JobService.InsertJob"
| extend job_type = tostring(parse_json(metadata_s).jobChange.job.jobConfig.type)
| where job_type == "EXTRACT"
| extend destination_uri = tostring(parse_json(metadata_s).jobChange.job.jobConfig.extractConfig.destinationUris[0])
| extend dest_bucket = extract(@"^gs://([^/]+)/", 1, destination_uri)
| where isnotempty(destination_uri) and not(dest_bucket in (authorized_buckets))
| summarize extract_event_count = count(),
            destinations = make_set(destination_uri)
        by principalEmail_s, callerIp_s, bin(TimeGenerated, 5m)
""",
    "Bigquery.T9": """
let lookback = 1h;
GCPAuditLogs_CL
| where TimeGenerated > ago(lookback)
| where serviceName_s == "bigquery.googleapis.com"
| where methodName_s == "google.cloud.bigquery.v2.JobService.InsertJob"
| extend statement_type = tostring(parse_json(metadata_s).jobChange.job.jobConfig.queryConfig.statementType)
| where statement_type == "SELECT"
| extend bytes_processed = tolong(parse_json(metadata_s).jobChange.job.jobStats.queryStats.totalProcessedBytes)
| extend query_text = tostring(parse_json(metadata_s).jobChange.job.jobConfig.queryConfig.query)
| extend referenced_table_count = array_length(parse_json(metadata_s).jobChange.job.jobStats.queryStats.referencedTables)
| extend rule_match = case(
        query_text matches regex @"(?i)select\\s+\\*\\s+from" and bytes_processed > 1073741824, "select_star_large_scan",
        bytes_processed > 53687091200, "oversized_scan",
        referenced_table_count >= 10, "broad_table_fanout",
        ""
  )
| where isnotempty(rule_match)
| project TimeGenerated, principalEmail_s, callerIp_s, rule_match, bytes_processed, referenced_table_count,
          query_preview = substring(query_text, 0, 240)
""",
}


def emit(threat: Threat, _signals: dict[str, PermissionSignal]) -> str | None:
    body = _QUERIES.get(threat.id)
    if body is None:
        return None
    return _HEADER.format(threat_id=threat.id, threat_name=threat.name) + body.strip() + "\n"
