"""Emit Splunk SPL searches for the Splunk GCP Add-on data model."""
from __future__ import annotations

from ..loader import Threat
from ..permission_map import PermissionSignal

_HEADER = """\
# AUTO-GENERATED by tools/threatmodel_compiler. DO NOT EDIT BY HAND.
# Source threat: {threat_id} — {threat_name}
# Index assumption: GCP audit logs in `index=gcp sourcetype=google:gcp:pubsub:message`
# (Splunk Add-on for Google Cloud Platform). Adjust the base search to your environment.
"""


_SEARCHES = {
    "Bigquery.T1": """
index=gcp sourcetype=google:gcp:pubsub:message
data.protoPayload.serviceName=bigquery.googleapis.com
(data.protoPayload.methodName="google.cloud.bigquery.v2.TableService.DeleteTable"
 OR data.protoPayload.methodName="google.cloud.bigquery.v2.DatasetService.DeleteDataset"
 OR data.protoPayload.methodName="tableservice.delete"
 OR data.protoPayload.methodName="datasetservice.delete")
NOT data.protoPayload.authenticationInfo.principalEmail="*@gserviceaccount.com"
| stats count as event_count
        values(data.protoPayload.resourceName) as resource
        values(data.protoPayload.requestMetadata.callerIp) as caller_ip
  by data.protoPayload.authenticationInfo.principalEmail data.protoPayload.methodName
| where event_count >= 1
""",
    "Bigquery.T6": """
index=gcp sourcetype=google:gcp:pubsub:message
data.protoPayload.serviceName=bigquery.googleapis.com
data.protoPayload.methodName="google.cloud.bigquery.v2.JobService.InsertJob"
data.protoPayload.metadata.jobChange.job.jobConfig.type=EXTRACT
| eval destination_uri=mvindex('data.protoPayload.metadata.jobChange.job.jobConfig.extractConfig.destinationUris{}', 0)
| where NOT match(destination_uri, "^gs://(authorized-export-bucket-1|authorized-export-bucket-2)/")
| stats count as extract_event_count
        values(data.protoPayload.requestMetadata.callerIp) as caller_ip
        values(destination_uri) as destinations
  by data.protoPayload.authenticationInfo.principalEmail
""",
    "Bigquery.T9": """
index=gcp sourcetype=google:gcp:pubsub:message
data.protoPayload.serviceName=bigquery.googleapis.com
data.protoPayload.methodName="google.cloud.bigquery.v2.JobService.InsertJob"
data.protoPayload.metadata.jobChange.job.jobConfig.queryConfig.statementType=SELECT
| eval bytes_processed=tonumber('data.protoPayload.metadata.jobChange.job.jobStats.queryStats.totalProcessedBytes')
| eval query_text='data.protoPayload.metadata.jobChange.job.jobConfig.queryConfig.query'
| eval referenced_table_count=mvcount('data.protoPayload.metadata.jobChange.job.jobStats.queryStats.referencedTables{}')
| eval rule_match=case(
        match(lower(query_text), "select\\s+\\*\\s+from") AND bytes_processed > 1073741824, "select_star_large_scan",
        bytes_processed > 53687091200, "oversized_scan",
        referenced_table_count >= 10, "broad_table_fanout"
  )
| where isnotnull(rule_match)
| table _time data.protoPayload.authenticationInfo.principalEmail rule_match bytes_processed referenced_table_count query_text
""",
}


def emit(threat: Threat, _signals: dict[str, PermissionSignal]) -> str | None:
    body = _SEARCHES.get(threat.id)
    if body is None:
        return None
    header = _HEADER.format(threat_id=threat.id, threat_name=threat.name)
    return header + "\n" + body.strip() + "\n"
